# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc8ae92f1216a6b3637a70bf694eb520a4ee9ca32cb4bfea0840213a8994a1cd49f631371e01daf6694fa98a2717f2b1b5b667e68233aeae9a05563f503e2e74

test:
  secret_key_base: d21064ee26297a9e54e727abe52d37621b6c92992117df00add9acd70a12cc9c57ad6706d2a9ddb256aa43a7bc710dded63633329d500e755c94dec823677e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
